@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 24 14:35:52 -0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Add_Sub_testbench_behav -key {Behavioral:sim_1:Functional:Add_Sub_testbench} -tclbatch Add_Sub_testbench.tcl -view C:/Users/izakw/OneDrive/Documents/GitHub/Floating-Point-Adder-Subtracter/Floating_Point_Adder_Subtractor/pre_normalize_testbench_behav.wcfg -view C:/Users/izakw/OneDrive/Documents/GitHub/Floating-Point-Adder-Subtracter/Floating_Point_Adder_Subtractor/Add_Sub_testbench_behav.wcfg -log simulate.log"
call xsim  Add_Sub_testbench_behav -key {Behavioral:sim_1:Functional:Add_Sub_testbench} -tclbatch Add_Sub_testbench.tcl -view C:/Users/izakw/OneDrive/Documents/GitHub/Floating-Point-Adder-Subtracter/Floating_Point_Adder_Subtractor/pre_normalize_testbench_behav.wcfg -view C:/Users/izakw/OneDrive/Documents/GitHub/Floating-Point-Adder-Subtracter/Floating_Point_Adder_Subtractor/Add_Sub_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
